endpoint for Master ID project
adsupnow/odoo pull request #356
Opened 2022-01-26 09:14 UTC by Vlad-CL

# JIRA

https://clxmedia.atlassian.net/browse/CLXD-1689

# Description

API endpoint for Master ID data. 
Odoo will return information regarding the connections configured for client(c) and budgets for connected subscriptions

2022-01-26 15:33 UTC, toddcd commented on clx_subscription_creation/controllers/portal.py
> +            return {"status": 404, "response": {"error": "partner_id is mandatory parameter."}}
should this be a 400 Bad Request?

2022-01-26 15:34 UTC, toddcd commented on clx_subscription_creation/controllers/portal.py
>              return {"status": 404, "response": {"error": "Access Token is wrong"}}
this should be 401 or 403

2022-01-26 15:42 UTC, toddcd approved these changes

2022-01-26 16:05 UTC, dmontooth commented on clx_subscription_creation/controllers/portal.py
>              return {"status": 404, "response": {"error": "Access Token is wrong"}}
This should be 401. 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

2022-01-26 16:05 UTC, dmontooth commented on clx_subscription_creation/controllers/portal.py
> +            return {"status": 404, "response": {"error": "partner_id is mandatory parameter."}}
Yes. This should be 400.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

2022-01-26 16:07 UTC, dmontooth requested changes
Need to update a couple of HTTP response codes

2022-01-26 16:30 UTC, Vlad-CL commented on clx_subscription_creation/controllers/portal.py
>              return {"status": 404, "response": {"error": "Access Token is wrong"}}
Good point, thank you

2022-01-26 16:30 UTC, Vlad-CL commented on clx_subscription_creation/controllers/portal.py
> +            return {"status": 404, "response": {"error": "partner_id is mandatory parameter."}}
True

2022-01-26 17:53 UTC, Vlad-CL commented
response codes updated

2022-01-27 17:10 UTC, dmontooth approved these changes

2022-01-27 17:16 UTC, merged