bill.com update #Poonam
adsupnow/odoo pull request #377
Opened 2022-02-22 18:13 UTC by vishalkhichadiyabista

# JIRA

Replace this with a link to the JIRA ticket

# Description

Please replace this paragraph with a summary of the change and/or which issue is fixed. Include relevant motivation and context. List any dependencies that are required for this change. For UI changes, include screenshots when necessary.

2022-02-22 18:45 UTC, dmontooth commented on bista_odoo_bill_com_connector/models/account_move.py
> +        # self.check_line_description()
Is this line not needed? If not, please remove it rather than comment it out

2022-02-22 18:46 UTC, dmontooth commented on bista_odoo_bill_com_connector/wizard/bulk_send_bill_com.py
> +        # invoice_brw.check_line_description()
Is this line not needed? If not, please remove it rather than comment it out

2022-02-22 18:47 UTC, dmontooth requested changes
There are lines commented out that, if not needed, should be removed

2022-02-23 18:16 UTC, vishalkhichadiyabista commented on bista_odoo_bill_com_connector/wizard/bulk_send_bill_com.py
> +        # invoice_brw.check_line_description()
removed!!!

2022-02-23 18:17 UTC, vishalkhichadiyabista commented
@dmontooth I've removed the lines as you asked.

2022-02-24 17:52 UTC, Vlad-CL approved these changes

2022-02-24 18:12 UTC, Vlad-CL approved these changes

2022-02-28 15:15 UTC, dmontooth approved these changes

2022-02-28 16:03 UTC, merged