Clxd 2086
adsupnow/odoo pull request #440
Opened 2022-05-17 17:43 UTC by toddcd

# JIRA

[CLXD-2086](https://clxmedia.atlassian.net/browse/CLXD-2086)

# Description

This contains a new module with the primary purpose of exposing data for data warehouse consumption. Initially, 3 endpoints have been created to help seed the data warehouse with basic company information. This is a first pass and will no doubt that the data points will need to be updated in the future as feed back from the business units is received. 
- localhost:8069/dw/companies
`  {
                    "master_id": 1,
                    "company_name": "Conversion Logix",
                    "vertical": "local",
                    "address": {
                        "primary": {
                            "street": "17921 Bothell Everett Highway",
                            "street2": "Suite 105",
                            "city": "Bothell",
                            "state": "WA",
                            "zip": "98012"
                        },
                        "mailing": {
                            "street": "17921 Bothell Everett Highway",
                            "street2": "Suite 105",
                            "city": "Bothell",
                            "state": "WA",
                            "zip": "98012"
                        }
                    },
                    "homepage_urls": "http://conversionlogix.com/",
                    "account_mgr": {
                        "name": "Jeanene Steinberg",
                        "email": "jeanenes@clxmedia.com"
                    },
                    "time_zone": "pacific"
                },`
- localhost:8069/dw/contactroles
` {
                    "id": 63535,
                    "master_id": 1,
                    "name": "Kristen Vogel",
                    "email": "kristenv@clxmedia.com",
                    "roles": "4-Billing Contact"
                },`
- localhost:8069/dw/subscriptions
`{
                    "id": 37122,
                    "product_name": "Email-One Time Email",
                    "product_id": 115,
                    "master_id": 54390,
                    "company_name": "Whitewater Park Apartments",
                    "is_active": true,
                    "cooped": false,
                    "updated_at": "2022-05-09 21:13:27"
                },`

2022-05-17 18:54 UTC, dmontooth commented on clx_data_warehouse/controllers/company_controllers.py
> +    @http.route(["/dw/companies"], type="json", auth="none", csrf=False, methods=["GET"])
Minor: "dw" could be more descriptive. "datawarehouse" or something that shows intent right away.

2022-05-17 18:56 UTC, Vlad-CL approved these changes
I just want to bring your attention you are merging to the Staging, not QA

2022-05-17 18:56 UTC, Vlad-CL commented on clx_data_warehouse/__manifest__.py
> +        # "data/schedulers.xml",
can you remove?

2022-05-17 18:56 UTC, Vlad-CL commented on clx_data_warehouse/demo/demo.xml
> +-->
do we need this?

2022-05-17 18:56 UTC, Vlad-CL commented on clx_data_warehouse/models/models.py
> +#             record.value2 = float(record.value) / 100
do we need this?

2022-05-17 18:56 UTC, Vlad-CL commented on clx_data_warehouse/views/templates.xml
> +-->
do we need this?

2022-05-17 18:56 UTC, Vlad-CL commented on clx_data_warehouse/views/views.xml
> +-->
Do we need all these commented?

2022-05-17 19:00 UTC, toddcd commented on clx_data_warehouse/controllers/company_controllers.py
> +    @http.route(["/dw/companies"], type="json", auth="none", csrf=False, methods=["GET"])
done

2022-05-17 19:19 UTC, dmontooth commented on clx_data_warehouse/controllers/contact_role_controllers.py
> +    @http.route(["/dw/contactroles"], type="json", auth="none", csrf=False, methods=["GET"])
dw suggestion

2022-05-17 19:21 UTC, dmontooth commented on clx_data_warehouse/models/models.py
> +# -*- coding: utf-8 -*-
is any of this needed?

2022-05-17 19:21 UTC, dmontooth commented on clx_data_warehouse/views/templates.xml
> +            <li t-foreach="objects" t-as="object">
is this needed?

2022-05-17 19:21 UTC, dmontooth commented on clx_data_warehouse/views/views.xml
> +<!--
is this needed?

2022-05-17 19:45 UTC, btaustin commented on clx_data_warehouse/controllers/company_controllers.py
> +        return company_detail_results
You need to have constraints available for `updated_since` so the pipeline can request the delta instead of a full dump every time.

2022-05-17 19:46 UTC, btaustin commented on clx_data_warehouse/controllers/contact_role_controllers.py
> +        }
Same `updated_since` comment here.

2022-05-17 19:48 UTC, btaustin commented on clx_data_warehouse/controllers/subscription_controllers.py
> +            sub_array.append(subscription)
How does `subscription_result` differ from `sub_array`?

2022-05-17 19:50 UTC, btaustin requested changes
Given the size of the source data collections, we really need to have the `updated_since` constraint in place from the beginning.

2022-05-17 20:04 UTC, btaustin commented on clx_data_warehouse/controllers/subscription_controllers.py
> +            sub_array.append(subscription)
From @toddcd via Slack: "`subscription_result` is the flat SQL results with no keys. I use that to build the subscription objects and add to the `sub_array` which is the payload"

Thanks! I completely missed that.

2022-05-18 00:13 UTC, toddcd commented on clx_data_warehouse/controllers/company_controllers.py
> +        return company_detail_results
updated_since param has been added. if not provided, last_updated is set to the last 2 hours

2022-05-18 00:13 UTC, toddcd commented on clx_data_warehouse/controllers/contact_role_controllers.py
> +        }
updated_since param has been added. if not provided, last_updated is set to the last 2 hours

2022-05-18 00:13 UTC, toddcd commented on clx_data_warehouse/controllers/subscription_controllers.py
> +            sub_array.append(subscription)
np 👍

2022-05-18 00:15 UTC, toddcd commented on clx_data_warehouse/__manifest__.py
> +        # "data/schedulers.xml",
done

2022-05-18 00:15 UTC, toddcd commented on clx_data_warehouse/demo/demo.xml
> +-->
done

2022-05-18 00:15 UTC, toddcd commented on clx_data_warehouse/views/templates.xml
> +-->
done

2022-05-18 00:15 UTC, toddcd commented on clx_data_warehouse/views/views.xml
> +-->
done

2022-05-18 00:15 UTC, toddcd commented on clx_data_warehouse/views/views.xml
> +<!--
done

2022-05-18 01:10 UTC, btaustin approved these changes

2022-05-18 14:44 UTC, merged